version: '3.1'
services:
  arena:
     container_name: arena
     working_dir: /backend/arena
     restart: always
     image: node
     command: "npm run install_and_run"
     volumes:
       - ../backend:/backend
     ports:
       - 4567:4567
     depends_on:
       - redis
     links:
       - redis   
  harvestor:
     container_name: harvestor
     working_dir: /backend/harvest
     restart: always
     image: node
     command: "npm run install_and_run"
     volumes:
       - ../backend:/backend
     depends_on:
       - elasticsearch
       - redis
     links:
       - elasticsearch
       - redis            
  angular_nginx:
    container_name: angular_nginx 
    image: angular_nginx
    build: angularBuild
    restart: always
    volumes:
       - ../RES:/frontend
       - ./default.conf:/etc/nginx/sites-available/default 
    ports:
       - 80:80
    depends_on:
       - elasticsearch
       - kibana
    links:
       - elasticsearch
       - kibana   
  redis:
      container_name: redis
      image: redis
      restart: always
      volumes:
        - ./redisData:/data
      ports:
        - 6379:6379
  elasticsearch:
      image: elasticsearch:6.6.1
      container_name: elasticsearch
      restart: always
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - ./esData:/usr/share/elasticsearch/data
        - ./esConfig:/usr/share/elasticsearch/config
      ports:
        - 9200:9200
        - 9300:9300
  kibana:
    container_name: kibana
    restart: always
    image: kibana:6.6.1
    depends_on:
      - elasticsearch
    links:
      - elasticsearch  
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200        
            